package project.boundaries;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import project.controllers.ThietBiController;
import project.controllers.UpdateTable;
import project.entities.ThietBi;
import project.utils.ConnectionUtils;

@SuppressWarnings("serial")
public class ThietBiForm extends javax.swing.JFrame {

	/**
	 * Creates new form ThietBi
	 */

	public static String sql = "SELECT * FROM newschema.thietbi order by matb,tentb,madv,tskt,gia,trangthai,nsx,thoigiancap";

	public static String matb; // biến này lưu tạm mã khi nhấn lên 1 dòng trong
								// bảng phục vụ cho hàm Update
	ThietBiController suatb = new ThietBiController();
	public static Connection conn;

	static {
		try {
			conn = ConnectionUtils.getConnection();
		} catch (ClassNotFoundException | SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public static PreparedStatement pst = null;
	public static ResultSet rs = null;

	public ThietBiForm() {
		super("Quản lý vật tư thiết bị văn phòng");
		initComponents();
		this.setLocationRelativeTo(null); // cho giao diện ra giữa màn hình

		showCT();
		ProcessCrt(true);
		DataComboBox();
		this.txtmatb.setEditable(false);
	}

	public void showCT() {
		UpdateTable.LoadData(sql, tbthietbi);
		UpdateTable.LoadData(sql, jTable2);

		this.lbTong.setText("Tổng cố có " + this.tbthietbi.getRowCount() + " thiết bị");
	}

	public void ProcessCrt(boolean b) {

		this.BT_ghilai.setEnabled(b);
		this.BT_huybo.setEnabled(b);

	}

	// load dữ liệu vào combobox
	@SuppressWarnings("unchecked")
	public void DataComboBox() {
		String sql1 = " SELECT * FROM newschema.donvi";
		try {
			PreparedStatement pst = conn.prepareStatement(sql1);
			ResultSet rs = pst.executeQuery();
			while (rs.next()) {
				this.cbmadv.addItem(rs.getString("madv"));
				this.cbdv.addItem(rs.getString("madv"));

			}
		} catch (SQLException | HeadlessException e) {
			JOptionPane.showMessageDialog(null, e);
		}

		String sql2 = " SELECT DISTINCT nsx FROM newschema.thietbi";
		try {
			PreparedStatement pst = conn.prepareStatement(sql2);
			ResultSet rs = pst.executeQuery();
			while (rs.next()) {
				this.cbcungcap.addItem(rs.getString("nsx"));

			}
		} catch (SQLException | HeadlessException e) {
			JOptionPane.showMessageDialog(null, e);
		}
		String sql3 = " SELECT DISTINCT trangthai FROM newschema.thietbi";
		try {
			PreparedStatement pst = conn.prepareStatement(sql3);
			ResultSet rs = pst.executeQuery();
			while (rs.next()) {
				this.cbtinhtrang.addItem(rs.getString("trangthai"));

			}
		} catch (SQLException | HeadlessException e) {
			JOptionPane.showMessageDialog(null, e);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane5 = new javax.swing.JTabbedPane();
		jFrame1 = new javax.swing.JFrame();
		jLabel1 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jTabbedPane2 = new javax.swing.JTabbedPane();
		jTabbedPane4 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		txtmatb = new javax.swing.JTextField();
		txttentb = new javax.swing.JTextField();
		txttskt = new javax.swing.JTextField();
		txtgia = new javax.swing.JTextField();
		txtnsx = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		tbthietbi = new javax.swing.JTable();
		BT_ghilai = new javax.swing.JButton();
		BT_huybo = new javax.swing.JButton();
		lbTong = new javax.swing.JLabel();
		txtthoigiancap = new com.toedter.calendar.JDateChooser();
		cbmadv = new javax.swing.JComboBox();
		cbtrangthai = new javax.swing.JComboBox();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		cbdv = new javax.swing.JComboBox();
		cbtinhtrang = new javax.swing.JComboBox();
		cbcungcap = new javax.swing.JComboBox();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jLabel17 = new javax.swing.JLabel();
		txtloctheoten = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();

		javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
		jFrame1Layout
				.setHorizontalGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, Short.MAX_VALUE));
		jFrame1Layout.setVerticalGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setSize(new java.awt.Dimension(0, 0));

		jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(204, 0, 0));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/device.png"))); // NOI18N
		jLabel1.setText("            Thiết bị");

		jTabbedPane1.addTab("Xem thông tin thiết bị", new javax.swing.ImageIcon(getClass().getResource("/Icon/Reports-icon.png")), jTabbedPane2); // NOI18N
		jTabbedPane1.addTab("Thêm thiết bị", new javax.swing.ImageIcon(getClass().getResource("/Icon/Back-icon.png")), jTabbedPane4); // NOI18N

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(204, 0, 0));
		jLabel2.setText("Sửa thiết bị");

		jLabel3.setText("Mã thiết bị");

		jLabel4.setText("Tên thiết bị");

		jLabel5.setText("Mã đơn vị");

		jLabel6.setText("TSKT");

		jLabel7.setText("Giá");

		jLabel8.setText("Trạng thái");

		jLabel9.setText("Nhà sản xuất");

		jLabel10.setText("Thời gian cấp");

		txttentb.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txttentbActionPerformed(evt);
			}
		});

		tbthietbi.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null, null }, { null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null }, { null, null, null, null, null, null, null, null } },
				new String[] { "Mã thiết bị", "Tên thiết bị", "ĐVSD", "Thông số kỹ thuật", "Giá", "Trạng thái", "Nhà SX", "Thời gian cấp" }));
		tbthietbi.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tbthietbiMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tbthietbi);

		BT_ghilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pencil-icon.png"))); // NOI18N
		BT_ghilai.setText("Ghi lại");
		BT_ghilai.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BT_ghilaiActionPerformed(evt);
			}
		});

		BT_huybo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/button_cancel.png"))); // NOI18N
		BT_huybo.setText("Hủy bỏ");
		BT_huybo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BT_huyboActionPerformed(evt);
			}
		});

		lbTong.setText("Tổng số");

		txtthoigiancap.setToolTipText("02/12/2016");
		txtthoigiancap.setDateFormatString("dd,MMM,yyyy");

		cbtrangthai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0" }));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel1Layout.createSequentialGroup().addGap(22, 22, 22)
												.addGroup(
														jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel3)
														.addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)).addGap(54, 54,
												54).addGroup(
														jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(jPanel1Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																		.addComponent(BT_ghilai)
																		.addComponent(txtmatb, javax.swing.GroupLayout.DEFAULT_SIZE, 164,
																				Short.MAX_VALUE)
																		.addComponent(txttentb)
																		.addComponent(txttskt, javax.swing.GroupLayout.Alignment.TRAILING))
												.addComponent(cbmadv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(47, 47, 47))
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jLabel8)
										.addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
								.addGap(30, 30, 30)))
						.addGroup(jPanel1Layout.createSequentialGroup().addComponent(BT_huybo).addPreferredGap(
								javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(txtgia, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE).addComponent(txtnsx))
						.addComponent(txtthoigiancap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(cbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(277, 277, 277).addComponent(jLabel2,
										javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(lbTong)))
						.addContainerGap(214, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup().addGap(18, 18, 18)
				.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(27, 27, 27)
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(jLabel7)
						.addComponent(txtmatb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(25, 25, 25)
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4).addComponent(jLabel8)
						.addComponent(txttentb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(cbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(29, 29, 29)
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(cbmadv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(txttskt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5)
										.addComponent(jLabel9).addComponent(txtnsx, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(30, 30, 30)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(txtthoigiancap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel10)
												.addComponent(jLabel6)))))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(BT_ghilai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(BT_huybo))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(41, 41, 41)
				.addComponent(lbTong).addContainerGap(86, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Sửa thiết bị", new javax.swing.ImageIcon(getClass().getResource("/Icon/gh lại.gif")), jPanel1); // NOI18N

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 794, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 560, Short.MAX_VALUE));

		jTabbedPane1.addTab("Xóa thiết bị", new javax.swing.ImageIcon(getClass().getResource("/Icon/delete1.png")), jPanel2); // NOI18N

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(204, 0, 0));
		jLabel11.setText("Lọc danh sách thiết bị");

		jLabel12.setText("Đơn vị sử dụng");

		jLabel14.setText("Trạng thái");

		jLabel15.setText("Đơn vị cung cấp");

		cbdv.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cbdvActionPerformed(evt);
			}
		});

		cbcungcap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cbcungcapActionPerformed(evt);
			}
		});

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null, null }, { null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null }, { null, null, null, null, null, null, null, null } },
				new String[] { "Mã thiết bị", "Tên thiết bị", "ĐVSD", "Thông số kỹ thuật", "Giá", "Trạng thái", "Nhà SX", "Thời gian cấp" }));
		jScrollPane2.setViewportView(jTable2);

		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/OK.png"))); // NOI18N
		jButton3.setText("OK");
		jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton3MouseClicked(evt);
			}
		});
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/button_cancel_1.png"))); // NOI18N
		jButton4.setText("Reset");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jLabel17.setText("Lọc theo tên TB");

		txtloctheoten.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtloctheotenActionPerformed(evt);
			}
		});

		jButton5.setText("Thống kê");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(238, 238, 238).addComponent(jLabel11))
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(18, 18, 18)
										.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel3Layout.createSequentialGroup().addGap(122, 122, 122).addComponent(jButton3))
												.addGroup(jPanel3Layout.createSequentialGroup().addGap(112, 112, 112).addComponent(cbdv,
														javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(jLabel12).addComponent(jLabel17).addComponent(txtloctheoten,
														javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(160, 160, 160)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jButton4)
										.addGroup(jPanel3Layout.createSequentialGroup()
												.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel15).addComponent(jLabel14))
												.addGap(65, 65, 65)
												.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(cbtinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(cbcungcap, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGroup(
								jPanel3Layout.createSequentialGroup()
										.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(34, 34, 34).addComponent(jButton5)))
						.addContainerGap(74, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(jLabel11).addGap(18, 18, 18)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel15)
								.addComponent(cbcungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel17).addComponent(txtloctheoten, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(39, 39, 39)
				.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel12)
						.addComponent(cbdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel14).addComponent(cbtinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
				.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton4)).addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel3Layout.createSequentialGroup().addGap(67, 67, 67)
												.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(54, 54, 54))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel3Layout.createSequentialGroup()
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton5)
														.addGap(186, 186, 186)))));

		jTabbedPane1.addTab("Lọc danh sách thiết bị", new javax.swing.ImageIcon(getClass().getResource("/Icon/Start-Menu-Search-icon (1).png")),
				jPanel3); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jTabbedPane1))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTabbedPane1).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void BT_ghilaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BT_ghilaiActionPerformed
		// TODO add your handling code here:
		if (this.txtmatb.getText().length() == 0)
			JOptionPane.showMessageDialog(null, "Bạn vui lòng chọn dòng muốn sửa", "thông báo", 2);

		else if (this.txttentb.getText().length() == 0)
			JOptionPane.showMessageDialog(null, "Tên thiết bị không thể bỏ trống", "thông báo", 2);
		else if (this.txttskt.getText().length() == 0)
			JOptionPane.showMessageDialog(null, "Thông số ký thuật không thể bỏ trống", "thông báo", 2);
		else if (this.txtgia.getText().length() == 0)
			JOptionPane.showMessageDialog(null, "Giá không thể bỏ trống", "thông báo", 2);
		else if (this.txtnsx.getText().length() == 0)
			JOptionPane.showMessageDialog(null, "Nhà sản xuất không thể bỏ trống", "thông báo", 2);

		else {

			ThietBi tb;
			tb = new ThietBi(this.txtmatb.getText(), this.txttentb.getText(), cbmadv.getSelectedItem().toString(), this.txttskt.getText(),
					Double.parseDouble(this.txtgia.getText()), Integer.parseInt(cbtrangthai.getSelectedItem().toString()), this.txtnsx.getText(),
					this.txtthoigiancap.getDate());
			ThietBiController.SuaThietBi(tb);
			showCT();
			ProcessCrt(true);

			if (ThietBiController.SuaThietBi(tb)) {

				JOptionPane.showMessageDialog(null, "Bạn đã sửa thành công", "Thông báo", 1);
			}

		}

	}// GEN-LAST:event_BT_ghilaiActionPerformed

	private void BT_huyboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BT_huyboActionPerformed
		// TODO add your handling code here:
		JOptionPane.showMessageDialog(null, " Bạn có chắc chắn muốn hủy", "Thông Báo", 2);
		/*
		 * ThietBi main=new ThietBi(); this.setVisible(false);
		 * main.setVisible(true);
		 */

	}// GEN-LAST:event_BT_huyboActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		if (this.txtloctheoten.getText().length() == 0) {
			String mysql = "SELECT * from newschema.thietbi ";
			UpdateTable.LoadData(mysql, jTable2);
		} else {
			/*
			 * String sql = "SELECT * from thietbi WHERE tentb like N'%"
			 * +this.txtloctheoten.getText()+"%' or donvisudung like N'%"
			 * +this.cbdv.getSelectedItem()+"%'" + "or donvicungcap like N'%"
			 * +this.cbcungcap.getSelectedItem()"%' or tinhtang like'%"
			 * +this.cbtinhtrang.getSelectedItem()"%'";
			 */
			String sql5 = "SELECT * FROM thietbi where tentb like'%" + this.txtloctheoten.getText() + "%'";
			// + "or madv like N'%"+this.cbdv.getSelectedItem()+"%'or nsx like
			// N'%"+this.cbcungcap.getSelectedItem()+"%'or trangthai like
			// N'%"+this.cbtinhtrang.getSelectedItem()+"%'";
			// String sql1="SELECT* FROM thietbi where madv like
			// N'%"+this.cbdv.getSelectedItem()+"%'or nsx like
			// N'%"+this.cbcungcap.getSelectedItem()+"%'or trangthai like
			// N'%"+this.cbtinhtrang.getSelectedItem()+"%'";
			UpdateTable.LoadData(sql5, jTable2);

		}

		String sql6 = "SELECT * from thietbi WHERE madv like N'%" + this.cbdv.getSelectedItem() + "%' ";
		UpdateTable.LoadData(sql6, jTable2);

		String sql7 = "SELECT * from thietbi WHERE nsx like N'%" + this.cbcungcap.getSelectedItem() + "%' ";
		UpdateTable.LoadData(sql7, jTable2);

		/*
		 * String sql8 = "SELECT * from thietbi WHERE trangthai like '%"
		 * +this.cbtinhtrang.getSelectedItem()+"%' "; UpdateTable.LoadData(sql8,
		 * jTable2);
		 */

	}// GEN-LAST:event_jButton3ActionPerformed

	private void txttentbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txttentbActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txttentbActionPerformed

	private void tbthietbiMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tbthietbiMouseClicked
		// TODO add your handling code here:

		ProcessCrt(true);
		this.BT_ghilai.setEnabled(true);
		try {
			int row = this.tbthietbi.getSelectedRow();
			String IDrow = (this.tbthietbi.getModel().getValueAt(row, 0)).toString();
			String sql = "SELECT * FROM thietbi where matb='" + IDrow + "'";
			ResultSet rs = UpdateTable.ShowTextField(sql);
			if (rs.next()) {
				matb = rs.getString("matb");
				this.txtmatb.setText(rs.getString("matb"));
				this.txttentb.setText(rs.getString("tentb"));

				this.txttskt.setText(rs.getString("tskt"));
				this.txtgia.setText(rs.getString("gia"));
				this.txtnsx.setText(rs.getString("nsx"));
				this.txtthoigiancap.setDate(rs.getDate("thoigiancap"));

			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e);
		}

	}// GEN-LAST:event_tbthietbiMouseClicked

	private void txtloctheotenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtloctheotenActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtloctheotenActionPerformed

	private void cbdvActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbdvActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cbdvActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
		txtloctheoten.setText("");
		UpdateTable.LoadData(sql, jTable2);

	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton3MouseClicked
		// TODO add your handling code here:

	}// GEN-LAST:event_jButton3MouseClicked

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton5ActionPerformed

	private void cbcungcapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbcungcapActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cbcungcapActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ThietBiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ThietBiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ThietBiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ThietBiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ThietBiForm().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BT_ghilai;
	private javax.swing.JButton BT_huybo;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbcungcap;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbdv;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbmadv;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbtinhtrang;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbtrangthai;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JFrame jFrame1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JTabbedPane jTabbedPane4;
	@SuppressWarnings("unused")
	private javax.swing.JTabbedPane jTabbedPane5;
	private javax.swing.JTable jTable2;
	private javax.swing.JLabel lbTong;
	private javax.swing.JTable tbthietbi;
	private javax.swing.JTextField txtgia;
	private javax.swing.JTextField txtloctheoten;
	private javax.swing.JTextField txtmatb;
	private javax.swing.JTextField txtnsx;
	private javax.swing.JTextField txttentb;
	private com.toedter.calendar.JDateChooser txtthoigiancap;
	private javax.swing.JTextField txttskt;
	// End of variables declaration//GEN-END:variables

}